title: Court Chronicle
avatar: Basketball_Data_Analysis_Logo.png
description: The Home for Basketball Analytics from the Court Chronicle.
remote_theme: pages-themes/tactile@v0.2.0
plugins_dir: jekyll-remote-theme
