title: NBA Analytics
logo: \Photos\Basketball-Data-Analysis-Logo.png
description: Hi my name is Robert and I am a data analyst who also loves basketball. I put together this collection of my deep dives into the statistics and analytics that tell a secret story about the NBA and global basketball as we know it. Don't be shy, come explore!

