title: NBA Analytics
description: Hi my name is Robert and I a data analyst who also loves basketball. I decided to put together this collection of my deep dives into the statistics and analytics that tell a secret story about the NBA and global basketball as we know it. Don't be shy, come explore!
logo: "C:\Users\rober\OneDrive\Documents\GitHub\NBA-Analytics\Photos\Basketball-Data-Analysis-Logo.png"

